const map=L.map('explorerMap',{zoomControl:false}).setView([48.7758,9.1829],11);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,opacity:.88,attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);
let period='18',layerName='heat',gridLayer,borderLayer,geoData,summaries=[];const info=document.getElementById('infoCard'),dc=document.getElementById('districtCard'),ds=document.getElementById('districtSelect'),ps=document.getElementById('periodSelect'),ls=document.getElementById('layerSelect');
['Bad Cannstatt','Degerloch','Feuerbach','Mitte','Ost','Süd','Untertürkheim','Vaihingen','West','Zuffenhausen'].forEach(n=>ds.add(new Option(n,n)));
function setOptions(){const heat=ls.querySelector('option[value="heat"]');heat.disabled=period==='change';if(period==='change'&&layerName==='heat'){layerName='lst';ls.value='lst'}}
function field(){if(period==='change')return layerName+'_change';return layerName==='green'?'green_'+period:layerName+'_'+period}
function val(p){return Number(p[field()])}
function norm(p){let v=val(p);if(period==='change'){const r={lst:5,uhi:5,green:.15}[layerName];return Math.max(0,Math.min(100,50+v/r*50))}if(layerName==='lst')return Math.max(0,Math.min(100,(v-25)/25*100));if(layerName==='uhi')return Math.max(0,Math.min(100,(v+8)/24*100));return v}
function color(v){if(period==='change')return v>60?'#c43b2f':v<40?'#3677a8':'#d9d3c7';if(layerName==='green')return v>66?'#26734d':v>33?'#a8a640':'#d56a35';return v>66?'#c93d2c':v>33?'#e9a53a':'#32835d'}
function style(f){return{color:'rgba(255,255,255,.28)',weight:.55,fillColor:color(norm(f.properties)),fillOpacity:.67}}
function burden(v){return v>=67?'eine hohe':v>=34?'eine mittlere':'eine niedrige'}
function explain(p){let v=val(p);if(period==='change'){let dir=v>0?'zugenommen':v<0?'abgenommen':'sich kaum verändert';if(layerName==='lst')return `Die mittlere Landoberflächentemperatur hat ${dir} (${v>0?'+':''}${v.toFixed(1)} °C).`;if(layerName==='uhi')return `Der Wärmeinsel-Effekt hat ${dir} (${v>0?'+':''}${v.toFixed(1)} °C).`;return `Der mittlere NDVI-Wert hat ${dir} (${v>0?'+':''}${v.toFixed(3)}).`;}
if(layerName==='heat')return `Diese Zelle weist ${burden(v)} thermische Belastung im stadtweiten Vergleich auf. Der Index ist ein projektbezogener Vergleichswert, keine gemessene Lufttemperatur.`;
if(layerName==='lst')return `Die mittlere Landoberflächentemperatur beträgt ${v.toFixed(1)} °C. Sie beschreibt die Temperatur der Erdoberfläche, nicht die Luft- oder gefühlte Temperatur.`;
if(layerName==='uhi')return `Der UHI-Wert beträgt ${v.toFixed(1)} °C. Positive Werte zeigen eine stärkere Erwärmung gegenüber dem ländlichen Referenzraum des Forschungsdatensatzes.`;
return `Der Vegetationsindikator basiert auf NDVI. Höhere Werte stehen für stärkere Vegetationsausprägung und damit tendenziell mehr kühlendes Potenzial durch Schatten und Verdunstung.`}
function render(p){let q=period==='change'?'18':period;info.innerHTML=`<h2>Rasterzelle ${p.cell_id}</h2><p class="muted">${p.district||'Stuttgart'} · 250 × 250 m</p><div class="info-grid"><div class="kpi"><span>Heat Score</span><strong>${period==='change'?'–':p['heat_'+q]}</strong></div><div class="kpi"><span>Oberfläche</span><strong>${Number(p['lst_'+q]).toFixed(1)} °C</strong></div><div class="kpi"><span>Wärmeinsel</span><strong>${Number(p['uhi_'+q]).toFixed(1)} °C</strong></div><div class="kpi"><span>NDVI</span><strong>${Number(p['ndvi_'+q]).toFixed(3)}</strong></div></div><p>${explain(p)}</p>`}
function districtSummary(n){let s=summaries.find(x=>x.district===n);dc.innerHTML=`<h2>${n}</h2><p><strong>${Number(s.lst_18).toFixed(1)} °C</strong> mittlere LST · <strong>${Number(s.uhi_18).toFixed(1)} °C</strong> UHI · Vergleichsindex <strong>${Number(s.heat_18).toFixed(0)}</strong></p><p class="muted">LST-Veränderung: ${s.lst_change>=0?'+':''}${Number(s.lst_change).toFixed(1)} °C · UHI: ${s.uhi_change>=0?'+':''}${Number(s.uhi_change).toFixed(1)} °C · NDVI: ${s.ndvi_change>=0?'+':''}${Number(s.ndvi_change).toFixed(3)}</p>`}
function update(){setOptions();gridLayer.setStyle(style);document.getElementById('legendLow').textContent=period==='change'?'Abnahme':'niedrig';document.getElementById('legendHigh').textContent=period==='change'?'Zunahme':'hoch';document.getElementById('legendGradient').style.background=period==='change'?'linear-gradient(90deg,#3677a8,#d9d3c7,#c43b2f)':layerName==='green'?'linear-gradient(90deg,#d56a35,#a8a640,#26734d)':'linear-gradient(90deg,#32835d,#e9a53a,#c93d2c)'}
Promise.all([fetch('data/stuttgart-grid-placeholder.geojson').then(r=>r.json()),fetch('data/stuttgart-districts.geojson').then(r=>r.json()),fetch('data/district-summary.json').then(r=>r.json())]).then(([g,b,s])=>{geoData=g;summaries=s;gridLayer=L.geoJSON(g,{style,onEachFeature:(f,l)=>{l.on('mouseover',()=>{l.setStyle({weight:1.8,color:'#fff',fillOpacity:.85});render(f.properties)});l.on('mouseout',()=>gridLayer.resetStyle(l));l.on('click',()=>render(f.properties))}}).addTo(map);borderLayer=L.geoJSON(b,{style:{color:'#252525',weight:2,fillOpacity:0},interactive:false}).addTo(map);map.fitBounds(gridLayer.getBounds(),{padding:[35,35]});});
ps.onchange=e=>{period=e.target.value;update()};ls.onchange=e=>{layerName=e.target.value;update()};let cityGridLayerRef=null,districtDetailLayer=null,manifest=[];
fetch('data/district-manifest.json').then(r=>r.json()).then(m=>manifest=m);
function tooltip(term,text){return `${term}<span class="term-tip" tabindex="0" data-tip="${text}">?</span>`}
const defs={heat:'Projektbezogener Vergleichsindex aus Landoberflächentemperatur, Wärmeinsel-Effekt und Vegetationsdefizit. Keine gemessene Lufttemperatur.',lst:'Temperatur der Erdoberfläche. Sie kann deutlich von Luft- und gefühlter Temperatur abweichen.',uhi:'Städtische Hitzeinsel: stärkere Erwärmung gegenüber dem ländlichen Referenzraum, unter anderem durch Versiegelung, Bebauung und wenig Vegetation.',ndvi:'Satellitenbasierter Vegetationsindex. Höhere Werte weisen auf stärkere Vegetationsausprägung hin.'};
const oldRender=render;render=function(p){oldRender(p);document.querySelectorAll('#infoCard .kpi span').forEach((el,i)=>{const keys=['heat','lst','uhi','ndvi'];el.innerHTML=tooltip(el.textContent,defs[keys[i]])})};
ds.onchange=async e=>{let n=e.target.value;
if(!cityGridLayerRef)cityGridLayerRef=gridLayer;
if(!n){if(districtDetailLayer){map.removeLayer(districtDetailLayer);districtDetailLayer=null}if(!map.hasLayer(cityGridLayerRef))cityGridLayerRef.addTo(map);gridLayer=cityGridLayerRef;document.getElementById('resolutionNote').textContent='Auflösung: 250 × 250 m';map.fitBounds(gridLayer.getBounds(),{padding:[35,35]});dc.innerHTML='<p class="muted">Gesamtes Stadtgebiet.</p>';update();return}
let item=manifest.find(x=>x.district===n);if(!item)return;
if(map.hasLayer(cityGridLayerRef))map.removeLayer(cityGridLayerRef);if(districtDetailLayer)map.removeLayer(districtDetailLayer);
let data=await fetch(item.file).then(r=>{if(!r.ok)throw new Error('Detailraster '+r.status);return r.json()});
districtDetailLayer=L.geoJSON(data,{style,onEachFeature:(f,l)=>{l.on('mouseover',()=>{l.setStyle({weight:1.8,color:'#fff',fillOpacity:.85});render(f.properties)});l.on('mouseout',()=>districtDetailLayer.resetStyle(l));l.on('click',()=>render(f.properties))}}).addTo(map);
gridLayer=districtDetailLayer;document.getElementById('resolutionNote').textContent=`Auflösung: 125 × 125 m · ${item.cells} Zellen geladen`;districtSummary(n);map.fitBounds(districtDetailLayer.getBounds(),{padding:[70,70]});update()};
const d=document.getElementById('methodDialog');document.getElementById('methodBtn').onclick=()=>d.showModal();document.getElementById('closeMethod').onclick=()=>d.close();