const map=L.map('explorerMap',{zoomControl:false}).setView([48.7758,9.1829],12);
L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,opacity:.82,attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);
L.control.zoom({position:'bottomright'}).addTo(map);
let period='18',layerName='heat',gridLayer,geoData,summaries=[],hotspots=[];
const info=document.getElementById('infoCard'),districtCard=document.getElementById('districtCard'),districtSelect=document.getElementById('districtSelect');
const names=['Bad Cannstatt','Degerloch','Feuerbach','Mitte','Ost','Süd','Untertürkheim','Vaihingen','West','Zuffenhausen'];
names.forEach(n=>districtSelect.add(new Option(n,n)));
function field(){if(period==='change')return layerName+'_change';return layerName+'_'+period}
function raw(p){return p[field()]}
function norm(p){let v=Number(raw(p));if(period==='change'){const ranges={heat:20,lst:5,uhi:5,green:.15};return Math.max(0,Math.min(100,50+v/ranges[layerName]*50))}
if(layerName==='lst')return Math.max(0,Math.min(100,(v-28)/20*100));if(layerName==='uhi')return Math.max(0,Math.min(100,(v+5)/20*100));if(layerName==='green')return Number(p['green_'+period]);return v}
function color(v){if(period==='change')return v>60?'#c43b2f':v<40?'#3677a8':'#d9d3c7';if(layerName==='green')return v>66?'#26734d':v>33?'#a8a640':'#d56a35';return v>66?'#c93d2c':v>33?'#e9a53a':'#32835d'}
function style(f){return{color:'rgba(255,255,255,.42)',weight:.8,fillColor:color(norm(f.properties)),fillOpacity:.66}}
function grammar(score){return score>=67?'eine hohe':score>=34?'eine mittlere':'eine niedrige'}
function text(p){const v=raw(p),per=period==='18'?'2016–2020':period==='06'?'2004–2008':'zwischen beiden Zeiträumen';
if(period==='change'){const dir=Number(v)>0?'zugenommen':Number(v)<0?'abgenommen':'kaum verändert';const labels={heat:'Der projektbezogene thermische Vergleichsindex',lst:'Die mittlere Landoberflächentemperatur',uhi:'Der Wärmeinsel-Effekt',green:'Der Vegetationsindikator'};return `${labels[layerName]} hat ${dir}. Die Karte zeigt Veränderungen räumlich, nicht als Echtzeitentwicklung.`}
if(layerName==='heat')return `Diese Zelle weist ${grammar(Number(v))} thermische Belastung im stadtweiten Vergleich auf. Der Index bündelt reale LST-, UHI- und Vegetationsdaten und ist kein Messwert der Lufttemperatur.`;
if(layerName==='lst')return `Die mittlere Landoberflächentemperatur beträgt ${Number(v).toFixed(1)} °C. Sie beschreibt die Erwärmung der Oberfläche und ist nicht mit Luft- oder gefühlter Temperatur gleichzusetzen.`;
if(layerName==='uhi')return `Der UHI-Wert beträgt ${Number(v).toFixed(1)} °C. Positive Werte zeigen eine stärkere Erwärmung gegenüber dem ländlichen Referenzraum des Forschungsdatensatzes.`;
return `Der Vegetationsindikator basiert auf NDVI. Höhere Werte stehen für stärkere Vegetationsausprägung; Vegetation kann durch Schatten und Verdunstung zur Kühlung beitragen.`}
function render(p){info.innerHTML=`<h2>Rasterzelle ${p.cell_id}</h2><p class="muted">${p.district} · 250 × 250 m</p><div class="info-grid"><div class="kpi"><span>Heat Score</span><strong>${p['heat_'+(period==='change'?'18':period)]}</strong></div><div class="kpi"><span>Oberfläche</span><strong>${Number(p['lst_'+(period==='change'?'18':period)]).toFixed(1)} °C</strong></div><div class="kpi"><span>Wärmeinsel</span><strong>${Number(p['uhi_'+(period==='change'?'18':period)]).toFixed(1)} °C</strong></div><div class="kpi"><span>NDVI</span><strong>${Number(p['ndvi_'+(period==='change'?'18':period)]).toFixed(3)}</strong></div></div><p>${text(p)}</p>`}
function districtSummary(name){const s=summaries.find(x=>x.district===name);if(!s){districtCard.innerHTML='';return}districtCard.innerHTML=`<h2>${name}</h2><p><strong>${Number(s.lst_18).toFixed(1)} °C</strong> mittlere LST · <strong>${Number(s.uhi_18).toFixed(1)} °C</strong> UHI · Heat Score <strong>${Number(s.heat_18).toFixed(0)}</strong></p><p class="muted">LST-Veränderung gegenüber 2004–2008: ${Number(s.lst_change)>=0?'+':''}${Number(s.lst_change).toFixed(1)} °C.</p>`}
function update(){if(gridLayer)gridLayer.setStyle(style);document.getElementById('legendLow').textContent=period==='change'?'Abnahme':'niedrig';document.getElementById('legendHigh').textContent=period==='change'?'Zunahme':'hoch';document.getElementById('legendGradient').style.background=period==='change'?'linear-gradient(90deg,#3677a8,#d9d3c7,#c43b2f)':layerName==='green'?'linear-gradient(90deg,#d56a35,#a8a640,#26734d)':'linear-gradient(90deg,#32835d,#e9a53a,#c93d2c)'}
Promise.all([fetch('data/stuttgart-grid-placeholder.geojson').then(r=>r.json()),fetch('data/district-summary.json').then(r=>r.json()),fetch('data/hotspots.json').then(r=>r.json())]).then(([g,s,h])=>{geoData=g;summaries=s;hotspots=h;gridLayer=L.geoJSON(g,{style,onEachFeature:(f,l)=>{l.on('mouseover',()=>{l.setStyle({weight:2,color:'#fff',fillOpacity:.86});render(f.properties)});l.on('mouseout',()=>gridLayer.resetStyle(l));l.on('click',()=>render(f.properties))}}).addTo(map);map.fitBounds(gridLayer.getBounds(),{padding:[35,35]});});
document.getElementById('periodSelect').onchange=e=>{period=e.target.value;update()};document.getElementById('layerSelect').onchange=e=>{layerName=e.target.value;update()};
districtSelect.onchange=e=>{const n=e.target.value;if(!n){map.fitBounds(gridLayer.getBounds(),{padding:[35,35]});districtCard.innerHTML='<p class="muted">Gesamtes Untersuchungsgebiet.</p>';return}districtSummary(n);const subset=L.geoJSON({type:'FeatureCollection',features:geoData.features.filter(f=>f.properties.district===n)});map.fitBounds(subset.getBounds(),{padding:[80,80]})};
const d=document.getElementById('methodDialog');document.getElementById('methodBtn').onclick=()=>d.showModal();document.getElementById('closeMethod').onclick=()=>d.close();